version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: taskmanagement_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanagementdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: src/TaskManagement.Api/Dockerfile
    container_name: taskmanagement_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=taskmanagementdb;Username=postgres;Password=postgres
    depends_on:
      - postgres

volumes:
  pgdata:
